### ISSUE TITLE
IPv6 can communicate, but IPv4 still can't communicate!

### ISSUE THREAD

**Issue by shaozhai** [JonStratton/mesh-front-py#10]
![image](https://user-images.githubusercontent.com/3293135/98193625-a887fe80-1f58-11eb-870f-180079a0098e.png)
![image](https://user-images.githubusercontent.com/3293135/98193686-c05f8280-1f58-11eb-8bb9-0f5bc7fe7c9b.png)

**Comment by JonStratton** [comment]
Try clearing out "Wireless Address" and making sure "Mesh Interface Type" is set to "static" (note, there is a cosmetic bug that lists this as manual when coming back to the page, so make sure you set it to static when saving until that bug is fixed[next on my list]) then saving and rebooting.

If things look good, make sure the mesh interfaces see each other with the "sudo batctl n" command. Assuming they do, check to see if the bat0 interface has the ip address you set it too with the "ip a" command. If that is good, try to ping the other node directly via the bat0 interface with something like "ping -I bat0 192.168.199.2".

As these are starting to look like common debugging things, I think Im going to automate the and maybe make a "debug" page that checks this stuff automatically.

I'm going to close down the other issue you opened as Ive added the setup documentation. We can look at this latest issue together on this new ticket.

**Comment by JonStratton** [comment]
Based on other bug opened, It looks like you can now hit the IPs across noded.
