### ISSUE TITLE
Why hasn't it been updated?

### ISSUE THREAD

**Issue by shaozhai** [JonStratton/mesh-front-py#19]
Why hasn't it been updated?

**Comment by JonStratton** [comment]
Mostly because Ive been working on other projects. But also I created https://github.com/JonStratton/mesh-micro which, for my other project, which fits a little better. 

I'm not abandoning this project, and will probably make it compatible with mesh-micro eventually. Did you have a feature you wanted or a bug fix or something?

**Comment by JonStratton** [comment]
Not an issue

**Comment by shaozhai** [comment]
Upgrade and the problem is still there
